### ISSUE TITLE
git push..

### ISSUE THREAD

**Issue by dan4ik605743** [nix-community/NUR#365]
For which day I have been trying to make my own NUR repository. Staying with git push. Asks for login password. I do not understand what he needs to try to enter from sveogo all to no purpose. Made a repo: https://github.com/dan4ik605743/nur. Everything is as it should be. I edited repos.json, executed ./bin/nur format-manifest, made a git commit -m "add dan4ik605743 repository", and now I'm doing a git push. And that's all .. Help please.
![image](https://user-images.githubusercontent.com/86075850/122515651-f5c46680-d037-11eb-82ed-b820fdb5ae63.png)
![image](https://user-images.githubusercontent.com/86075850/122515733-12f93500-d038-11eb-97a9-b487c079b2d7.png)
![image](https://user-images.githubusercontent.com/86075850/122515785-23a9ab00-d038-11eb-831d-010d78ee9c2d.png)

**Comment by Mic92** [comment]
Hi! In order to make a pull request you need to fork the repo. Click on the fork button on this repo to make a fork.
Than clone the fork repo, make your change. Commit and push it. After you have pushed to your own fork, you can create a pull request. There is also github documentation on how to do pull requests from a forked repo.

**Comment by Mic92** [comment]
Here also with screenshots: https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by dan4ik605743** [comment]
> Here also with screenshots: https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

thanks, I'll try later
